version: "3.7"
services:
  agent_1:
    build:
      context: ./
      args:
        AGENT_FILE: "agent_1_standalone.py"
    environment:
      LOG_LEVEL: "DEBUG"
    ports:
      - 8081:80
  agent_2:
    build:
      context: ./
      args:
        AGENT_FILE: "agent_2_standalone.py"
    environment:
      LOG_LEVEL: "DEBUG"
    ports:
      - 8082:80
